In [1]:
import torch
import numpy as np

In [2]:
### Create a 3x4 tensor of random numbers:
x = torch.rand(3, 4)
print("Original tensor (3x4):")
print(x)
print("Shape:", x.shape)

Original tensor (3x4):
tensor([[0.6589, 0.3259, 0.8449, 0.6312],
        [0.3464, 0.9708, 0.1817, 0.2676],
        [0.3905, 0.8618, 0.6339, 0.1449]])
Shape: torch.Size([3, 4])


In [4]:
### Reshape operations
x1 = x.reshape(6, 2)
print("\nReshaped to 6 x 2:")
print(x1)
print("Shape:", x1.shape)
x2 = x.reshape(2, 6)
print("\nReshaped to 2 x 6:")
print(x2)
print("Shape:", x2.shape)


Reshaped to 6 x 2:
tensor([[0.6589, 0.3259],
        [0.8449, 0.6312],
        [0.3464, 0.9708],
        [0.1817, 0.2676],
        [0.3905, 0.8618],
        [0.6339, 0.1449]])
Shape: torch.Size([6, 2])

Reshaped to 2 x 6:
tensor([[0.6589, 0.3259, 0.8449, 0.6312, 0.3464, 0.9708],
        [0.1817, 0.2676, 0.3905, 0.8618, 0.6339, 0.1449]])
Shape: torch.Size([2, 6])


In [5]:
### Slicing
print("\nFirst row:")
print(x[0])

print("\nLast column:")
print(x[:, -1])

print("\nBottom-right 2x2 block:")
print(x[-2:, -2:])


First row:
tensor([0.6589, 0.3259, 0.8449, 0.6312])

Last column:
tensor([0.6312, 0.2676, 0.1449])

Bottom-right 2x2 block:
tensor([[0.1817, 0.2676],
        [0.6339, 0.1449]])
